---
title: "EM_t_dist"
author: "ziming"
date: "6/27/2022"
output: html_document
---

This is a demonstration file of current build of robust EM.
```{r}
library(MASS)
library(stats)
library(mvtnorm)
library(LaplacesDemon)
library(ggplot2)
library(ggpubr)
library(Matrix)
library(mixtools)
library(dplyr)
library(stats)
library(fossil)
library(mclust)
library(dplyr)
library(kableExtra)
library(knitr)
## Change the path
currentPath = getwd()
print(currentPath)
source("./plot_helper.R")
source("./rem_core.R")
source("./initial_cond.R")
source("./simulator.R")
```
## Data simulation
```{r}
cluster = 8
d = 2
separation = 26
n = 120
out_perc <- 0.1
cov_scale <- 1
lam = 3
```

```{r}
sim_info <- sim_mixture(cluster, d, separation, n, out_perc, cov_scale = cov_scale, outl_mode = 'cauchy')
ggplot() + geom_point(aes(x = sim_info$gauss[,1], y = sim_info$gauss[,2]), col = sim_info$label_in) + geom_point(aes(x = sim_info$outlier[,1], y = sim_info$outlie[,2]), shape = 4)+ xlab('axis 1') + ylab('axis 2')
orip <- ggplot() + geom_point(aes(x = sim_info$gauss[,1], y = sim_info$gauss[,2]), col = sim_info$label_in) + geom_point(aes(x = sim_info$outlier[,1], y = sim_info$outlie[,2]), shape = 4) 
```

## MCLUST
```{r}
NoiseInit_by_guess = sample(c(TRUE,FALSE), size = dim(sim_info$x)[1], 
                            replace = TRUE, prob = c(1,5)/6)
result_mclust = Mclust(sim_info$x, verbose=F, G=cluster, modelNames = "VVV",
                       initialization = list(noise = NoiseInit_by_guess),
                       control = emControl(tol=c(1.e-6, 1.e-7), itmax=15))
plot_mc(result_mclust)
p_mc <- plot_mc(result_mclust)
rand.index(sim_info$label, result_mclust$classification)
adjustedRandIndex(sim_info$label, result_mclust$classification)
classError(sim_info$label, result_mclust$classification)


classError(1*(sim_info$label == 0), 1*(result_mclust$classification == 0))
sum(result_mclust$classification == 0)/(n*cluster)
```

## Init with Mclust result
```{r}
init_cond <- initial_hier(sim_info, cluster, mode = 'denoise')
```

## RobustEM
```{r}
## Robust EM
result_robust <- EM_robust(sampleMat =  sim_info$x, c = cluster, d=d, lambda = lam, sigma_str = 'unstr', inits = init_cond)
rand.index(sim_info$label, as.numeric(result_robust$hard_assign_out))
adjustedRandIndex(sim_info$label, as.numeric(result_robust$hard_assign_out))
classError(sim_info$label, as.numeric(result_robust$hard_assign_out))
plot_rem(result_robust, sim_info$x)
p_rem <- plot_rem(result_robust, sim_info$x)

classError(1*(sim_info$label == 0), 1*(result_robust$hard_assign_out == 0))
sum(result_robust$hard_assign_out == 0)/(n*cluster)
```

## Init with hierachical
```{r}
init_cond_hc <- initial_hier(sim_info$x, cluster = cluster, 'hc')
result_robust_hc <- EM_robust(sampleMat =  sim_info$x, c = cluster, d=d, lambda = lam, sigma_str = 'unstr', inits = init_cond_hc)
rand.index(sim_info$label, as.numeric(result_robust_hc$hard_assign_out))
adjustedRandIndex(sim_info$label, as.numeric(result_robust_hc$hard_assign_out))
plot_rem(result_robust_hc, sim_info$x)
prem_hc <- plot_rem(result_robust_hc, sim_info$x)
classError(sim_info$label, as.numeric(result_robust_hc$hard_assign_out))

classError(1*(sim_info$label == 0), 1*(result_robust_hc$hard_assign_out == 0))
sum(result_robust_hc$hard_assign_out == 0)/(n*cluster)
```

```{r}
ggarrange(p_mc, p_rem,
          labels = c('mclust', 'RobustEM'),
          ncol = 2, nrow = 1, vjust = -0.1, hjust = -1.5, heights = 10, widths = 10)
```

## Const structrue test
In low dimension setting it is usually worse than unstr
```{r}
## It is possible that numerical instability arises here. Change lambda accordingly!
lam = 3
## As expected, the tilting of the covariance circle will be adjusted. The axis of the ellipses will be parallel to x and y axis
init_cond_hc <- initial_hier(sim_info, cluster, mode = 'denoise')
result_robust_hc <- EM_robust(sampleMat =  sim_info$x, c = cluster, d=d, lambda = lam, sigma_str = 'const', inits = init_cond_hc)
rand.index(sim_info$label, as.numeric(result_robust_hc$hard_assign_out))
adjustedRandIndex(sim_info$label, as.numeric(result_robust_hc$hard_assign_out))
plot_rem(result_robust_hc, sim_info$x)
prem_hc <- plot_rem(result_robust_hc, sim_info$x)
classError(sim_info$label, as.numeric(result_robust_hc$hard_assign_out))
classError(1*(sim_info$label == 0), 1*(result_robust_hc$hard_assign_out == 0))
sum(result_robust_hc$hard_assign_out == 0)/(n*cluster)
```
## Diagonal
```{r}
## It is possible that numerical instability arises here. Change lambda accordingly!
lam = 3
init_cond_hc <- initial_hier(sim_info, cluster, mode = 'denoise')
result_robust_hc <- EM_robust(sampleMat =  sim_info$x, c = cluster, d=d, lambda = lam, sigma_str = 'diag', inits = init_cond_hc)
rand.index(sim_info$label, as.numeric(result_robust_hc$hard_assign_out))
adjustedRandIndex(sim_info$label, as.numeric(result_robust_hc$hard_assign_out))
plot_rem(result_robust_hc, sim_info$x)
prem_hc <- plot_rem(result_robust_hc, sim_info$x)
classError(sim_info$label, as.numeric(result_robust_hc$hard_assign_out))
classError(1*(sim_info$label == 0), 1*(result_robust_hc$hard_assign_out == 0))
sum(result_robust_hc$hard_assign_out == 0)/(n*cluster)
```











