---
title: "EM_t_dist"
author: "ziming"
date: "6/27/2022"
output: html_document
---


```{r}
library(MASS)
library(stats)
library(mvtnorm)
library(LaplacesDemon)
library(ggplot2)
library(ggpubr)
library(Matrix)
library(mixtools)
library(dplyr)
library(stats)
library(fossil)
library(mclust)
library(dplyr)
library(kableExtra)
library(knitr)

source('C:/Users/njzmh/OneDrive/Desktop/REM_official/plot_helper.R')
source('C:/Users/njzmh/OneDrive/Desktop/REM_official/rem_core.R')
source('C:/Users/njzmh/OneDrive/Desktop/REM_official/initial_cond.R')
source('C:/Users/njzmh/OneDrive/Desktop/REM_official/simulator.R')
source('C:/Users/njzmh/OneDrive/Desktop/REM_official/simulations/test_cauchy2.R')
```

```{r}
cluster = 7
d = 2
separation = 26
n = 60
out_perc <- 0.1
cov_scale <- 1
lam = 3
```

```{r}
sim_info <- sim_mixture(cluster, d, separation, n, out_perc, cov_scale = cov_scale, outl_mode = 'unif')
ggplot() + geom_point(aes(x = sim_info$gauss[,1], y = sim_info$gauss[,2]), col = sim_info$label_in) + geom_point(aes(x = sim_info$outlier[,1], y = sim_info$outlie[,2]), shape = 4)+ xlab('axis 1') + ylab('axis 2')
orip <- ggplot() + geom_point(aes(x = sim_info$gauss[,1], y = sim_info$gauss[,2]), col = sim_info$label_in) + geom_point(aes(x = sim_info$outlier[,1], y = sim_info$outlie[,2]), shape = 4) 
```

## MCLUST
```{r}
NoiseInit_by_guess = sample(c(TRUE,FALSE), size = dim(sim_info$x)[1], 
                            replace = TRUE, prob = c(1,5)/6)
result_mclust = Mclust(sim_info$x, verbose=F, G=cluster, modelNames = "VVV",
                       initialization = list(noise = NoiseInit_by_guess),
                       control = emControl(tol=c(1.e-6, 1.e-7), itmax=15))
plot_mc(result_mclust)
p_mc <- plot_mc(result_mclust)
rand.index(sim_info$label, result_mclust$classification)
adjustedRandIndex(sim_info$label, result_mclust$classification)
classError(sim_info$label, result_mclust$classification)


classError(1*(sim_info$label == 0), 1*(result_mclust$classification == 0))
sum(result_mclust$classification == 0)/(n*cluster)
```

## Init with Mclust result
```{r}
init_cond <- initial_hier(sim_info, cluster, mode = 'denoise')
```


## RobustEM
```{r}
## Standard EM
## Robust EM
result_robust <- EM_robust(sampleMat =  sim_info$x, c = cluster, d=d, lambda = lam, sigma_str = 'unstr', inits = init_cond)
rand.index(sim_info$label, as.numeric(result_robust$hard_assign_out))
adjustedRandIndex(sim_info$label, as.numeric(result_robust$hard_assign_out))
classError(sim_info$label, as.numeric(result_robust$hard_assign_out))
plot_rem(result_robust, sim_info$x)
p_rem <- plot_rem(result_robust, sim_info$x)

classError(1*(sim_info$label == 0), 1*(result_robust$hard_assign_out == 0))
sum(result_robust$hard_assign_out == 0)/(n*cluster)
```

## Init with hierachical
```{r}
init_cond_hc <- initial_hier(sim_info$x, cluster = cluster)
result_robust_hc <- EM_robust(sampleMat =  sim_info$x, c = cluster, d=d, lambda = lam, sigma_str = 'unstr', inits = init_cond_hc)
rand.index(sim_info$label, as.numeric(result_robust_hc$hard_assign_out))
adjustedRandIndex(sim_info$label, as.numeric(result_robust_hc$hard_assign_out))
plot_rem(result_robust_hc, sim_info$x)
prem_hc <- plot_rem(result_robust_hc, sim_info$x)
classError(sim_info$label, as.numeric(result_robust_hc$hard_assign_out))

classError(1*(sim_info$label == 0), 1*(result_robust_hc$hard_assign_out == 0))
sum(result_robust_hc$hard_assign_out == 0)/(n*cluster)
```

```{r}
ggarrange(p_mc, p_rem,
          labels = c('mclust', 'RobustEM'),
          ncol = 2, nrow = 1, vjust = -0.1, hjust = -1.5, heights = 10, widths = 10)
```



```{r}
rdx_mc <- c()
ardx_mc <- c()
rdx_rb <- c()
ardx_rb <- c()
ce_mc <- c()
ceo_mc <- c()
ce_rb <- c()
ceo_rb <- c()
for (i in c(1:150)) {
    sim_info <- sim_cauchy(cluster, d, seperation, n, out_perc, cov_scale = cov_scale, df = 7)
    ## mclust
    init_cond <- initMCLUST(sim_info, cluster)
    result_mclust = Mclust(sim_info$x, verbose=F, G=cluster, modelNames = "VVV",
                           initialization = list(noise = NoiseInit_by_guess),
                           control = emControl(tol=c(1.e-6, 1.e-7), itmax=16))
    rdx_mc = c(rdx_mc, rand.index(sim_info$label, result_mclust$classification))
    ardx_mc = c(ardx_mc, adjustedRandIndex(sim_info$label, result_mclust$classification))
    ce_mc = c(ce_mc, classError(sim_info$label, result_mclust$classification)$errorRate)
    ceo_mc = c(ceo_mc, classError(1*(sim_info$label == 0), 1*(result_mclust$classification == 0))$errorRate)
    ## robust
    result_robust <- EM_robust(sampleMat =  sim_info$x, c = cluster, d=d, lambda = lam, sigma_str = 'unstr', inits = init_cond)
    rdx_rb = c(rdx_rb, rand.index(sim_info$label, as.numeric(result_robust_hc$hard_assign_out)))
    ardx_rb = c(ardx_rb, adjustedRandIndex(sim_info$label, as.numeric(result_robust_hc$hard_assign_out)))
    ce_rb = c(ce_rb, classError(sim_info$label, as.numeric(result_robust$hard_assign_out))$errorRate)
    ceo_rb = c(ceo_rb, classError(1*(sim_info$label == 0), 1*(result_robust$hard_assign_out == 0))$errorRate)

}
mclust_table <- as.data.frame(cbind(rdx_mc, ardx_mc, ce_mc, ceo_mc, rep(0, 150)))
names(mclust_table) <- c('Random Index', 'adjusted Random Index', 'classification error', 'outlier classification error', 'mode')
robust_table <- as.data.frame(cbind(rdx_rb, ardx_rb, ce_rb, ceo_rb, rep(1, 150)))
names(robust_table) <- c('Random Index', 'adjusted Random Index', 'classification error', 'outlier classification error', 'mode')
temp <- bind_rows(mclust_table,robust_table)
out <- temp %>% group_by(mode) %>% summarise(
    `Random Index` = mean(`Random Index`),
    `Adjusted Random Index` = mean(`adjusted Random Index`),
    `Classification Error` = mean(`classification error`),
    `Outlier Classification Error` = mean(`outlier classification error`),
)

out$mode <- c('mclust', 'robustEM')
ko <- kable(out)
ko
```








